### ISSUE TITLE
Does not work for this pdf

### ISSUE THREAD

**Issue by zenglian** [beatngu13/pdf-zoom-wizard#22] opened 2019-02-08 11:04 UTC
For below pdf,  set to "fit width" but the bookmarks remain "fit height".

https://github.com/loveincode/Java-Multi-thread-Programming/raw/master/src/main/resources/Java%E5%A4%9A%E7%BA%BF%E7%A8%8B%E7%BC%96%E7%A8%8B%E6%A0%B8%E5%BF%83%E6%8A%80%E6%9C%AF.pdf

**Comment by zenglian** [comment] 2019-02-08 11:05
By the way,  can it pls remember the last path/folder.

**Comment by beatngu13** [comment] 2019-02-08 14:17
Hi @zenglian, thank you for the PDF. I was able to reproduce the error, although I haven't found time yet to have a closer look. (I assume it's an encoding issue in the underlying PDF library since it can only find a single bookmark.)

Regarding:

>By the way, can it pls remember the last path/folder.

Yep, that would be helpful. Feel free to file a separate issue for this enhancement.

**Comment by beatngu13** [comment] 2019-02-08 17:13
Duplicate of #20.

**Comment by beatngu13** [comment] 2019-02-08 17:20
(Internal) note: We currently only modify `GoToDestination<?>`s, but these bookmarks are `LocalDestination`s. Nonetheless, this issues requires #20 to be fixed since it contains a bookmark with a broken destination ("7.8 本章总结 306").

**Closed** 2019-02-08 21:33 UTC
Labels: bug

**Comment by beatngu13** [comment] 2019-02-08 22:05
Fixed in [`v0.2.0`](https://github.com/beatngu13/pdf-zoom-wizard/releases/tag/v0.2.0).

**Comment by zenglian** [comment] 2019-02-09 04:49
Thanks for your quick fix!  I love you... :)
